services:
  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tododb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
